### ISSUE TITLE
Overcast/Washed Out

### ISSUE THREAD

**Issue by Awesomeplayer165** [starkdmi/BrightXDR#3]
When running with v3.0, it is clearly washed out. This doesn't happen on `BetterDisplay`, for example.

<img width="1503" alt="image" src="https://github.com/starkdmi/BrightXDR/assets/70717139/55ab92cd-684a-4934-a0e2-1f3d9cd7d932">

**Comment by Awesomeplayer165** [comment]
Although this is an SDR screenshot, the effect is still actually happening on my eyes.

**Comment by starkdmi** [comment]
I can confirm. It worked differently on previous macOS (Ventura, 13). 

By modifying [this](https://github.com/starkdmi/BrightXDR/blob/a5b6b4af7ccde05b1a74c137e5d5107a2da7c95d/BrightXDR/AppDelegate.swift#L43) line I see the natural colours again (probably not as bright as before):
```Swift
metalView = MetalView(frame: view.bounds, frameRate: 3, contrast: 1.0, brightness: 1.0)
```

You can play with `contrast`,`brightness` and `saturation` properties of [CIColorControls CIFilter](https://developer.apple.com/documentation/coreimage/cicolorcontrols) used in [MetalView.swift](https://github.com/starkdmi/BrightXDR/blob/a5b6b4af7ccde05b1a74c137e5d5107a2da7c95d/BrightXDR/MetalView.swift#L71).
