### ISSUE TITLE
Publish to homebrew

### ISSUE THREAD

**Issue by fregante** [starkdmi/BrightXDR#4]
It would be nice to be able to run this without having to run Xcode.

See also #2

**Comment by starkdmi** [comment]
@fregante That's a concept, not a well made application for daily use, but sometimes it's too bright outside though)

Just notarized, no other changes: [BrightXDR.app](https://github.com/user-attachments/files/17317704/BrightXDR.zip)

**Comment by fregante** [comment]
> not a well made application for daily use

Thank you! That actually works for me, it's more of a "just in case" thing
