### ISSUE TITLE
Request to Publish the APP

### ISSUE THREAD

**Issue by ansuff** [starkdmi/BrightXDR#5]
I was wondering if there are plans to publish this in a (.app) that could be run easily without the need for Xcode, thanks!

**Comment by starkdmi** [comment]
Hey, @ansuff, as I already [told](https://github.com/starkdmi/BrightXDR/issues/4#issuecomment-2403293957):
> That's just a concept, and not a well made application for daily use.

But if you still need it or want to try you could download it [here](https://github.com/user-attachments/files/17317704/BrightXDR.zip), it's ultra small.

**Comment by ansuff** [comment]
I’ve delved a bit deeper into this, and yes, you’re absolutely right. Thanks for your prompt response. Cheers!
